services:
  drone-follows-drone:
    tty: true
    build:
      context: ../docker
      dockerfile: Dockerfile
    volumes:
      - ../:/home/ubuntu/drone-follows-drone
      - data:/home/ubuntu/data
    # runtime: nvidia
    ports:
    - target: 8889
      published: 8889
      protocol: udp
      mode: host
    - target: 8890
      published: 8890
      protocol: udp
      mode: host
    - target: 11111
      published: 11111
      protocol: udp
      mode: host

volumes:
  data: