services:
  drone-follows-drone:
    tty: true
    build:
      context: ../docker
      dockerfile: Dockerfile
    volumes:
      - ../:/home/ubuntu/drone-follows-drone
      - data:/home/ubuntu/data
    # runtime: nvidia

volumes:
  data: