version: "3.9"

services:
  drone-follows-drone:
    tty: true
    build:
      context: ../docker
      dockerfile: Dockerfile
    volumes:
      - data:/home/ubuntu/data
    # runtime: nvidia

volumes:
  data: